### ISSUE TITLE
A bit more formal setproperties specification?

### ISSUE THREAD

**Issue by tkf** [JuliaObjects/ConstructionBase.jl#11]
It's nice that we have "constructor laws" for `constructorof`:

https://github.com/JuliaObjects/ConstructionBase.jl/blob/f3cf74ab2f5a5c89f9eadeef94a5c6d96f3bd680/src/ConstructionBase.jl#L33-L43

How about `setproperties`?  Maybe it would be better to specify that it has to follow lens laws?:

> For any valid set of properties `p₁`, `p₂`, ..., `pₙ`, following equalities must hold:
>
> 1\. You get what you set.
>
> ```julia
> let obj′ = setproperties(obj, ($p₁=v₁, $p₂=v₂, ..., $pₙ=vₙ))
>     @assert obj′.$p₁ == v₁
>     @assert obj′.$p₂ == v₂
>     ...
>     @assert obj′.$pₙ == vₙ
> end
> ```
>
> 2\. Setting what was already there changes nothing.
>
> ```julia
> @assert setproperties(obj, ($p₁=obj.$p₁, $p₂=obj.$p₂, ..., $pₙ=obj.$pₙ)) == obj
> ```
>
> 3\. The last set wins.
>
> ```julia
> let obj′ = setproperties(obj, ($p₁=v₁, $p₂=v₂, ..., $pₙ=vₙ)),
>     obj′′ = setproperties(obj′, ($p₁=w₁, $p₂=w₂, ..., $pₙ=wₙ))
>     @assert obj′′.$p₁ == w₁
>     @assert obj′′.$p₂ == w₂
>     ...
>     @assert obj′′.$pₙ == wₙ
> end
> ```

It's probably too obvious for anyone who wants to implement `setproperties`?  It could be destructing if you already get it.

OTOH, it's nice to know/specify that:

* The counter part of `setproperties` is `getproperty`, not `getfield`.
* It's OK to implement `setproperties` for crazy objects where `propertynames` may be undefined (e.g., an object may declare to have infinite number of properties).
* `PropertyLens` will satisfy the lens laws.

**Comment by jw3126** [comment]
We should document that `setproperties` is about `getproperty/propertynames` and not the fields. I think spelling out the lens laws does not hurt either. We probably should also specify that `setproperties` does not mutate the object.
