### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by jw3126** [JuliaObjects/ConstructionBase.jl#13]
Shall we tag a release? Anything missing? @tkf @rafaqz

**Comment by tkf** [comment]
I think it's good to go!  (I want to spend a bit more time in the documentation before the announcement, though.)

**Comment by jw3126** [comment]
Sure we can wait with the announcement.

**Comment by jw3126** [comment]
`@JuliaRegistrator register`

**Comment by jw3126** [comment]
`@JuliaRegistrator register`

**Comment by tkf** [comment]
It's released now! :tada:
