### ISSUE TITLE
Guidlines for writing constructorof constructors

### ISSUE THREAD

**Issue by rafaqz** [JuliaObjects/ConstructionBase.jl#26]
Flatten.jl provided `constructor_of` for Unitful.jl in requires, because flattening models with units is very common and ConstructorBase didn't exist. I'm going to put in a pull request at unitful to depend on ConstructionBase so that quantities can be reconstructed.

But I'm wondering what kind of standard form constructors should take. In this case the first type parameter `T` is determined by the `val` field we want to set, and is usually an AbstractFloat or Int. `D` and `U` need to persist through construction, but they come after `T`.

This is the updated version of what I had before ConstructionBase:

```julia
struct QuantityConstructor{D,U} end
QuantityConstructor{D,U}(x::T) where {T,D,U} = Quantity{T,D,U}(x)

ConstructionBase.constructorof(::Type{Quantity{T,D,U}}) where {T,D,U} = 
    QuantityConstructor{D,U}
```

Which stays out of the way of other `Quantity` constructors. But is there a simpler way of doing this that could become the standard practise?

**Comment by tkf** [comment]
I guess the dumbest solution would be

```julia
ConstructionBase.constructorof(::Type{T}) where {T <: Quantity} =
    x -> Quantity(x, unit(T))
```

though your solution may be better if you are going to read the output of `constructorof`.

If you can add a constructor to `Quantity`, maybe it's nicer to define

```julia
Quantity{<:Any, D, U}(val) where {D, U} = Quantity{typeof(val / unit(val)), D, U}(val)
```

and then

```julia
ConstructionBase.constructorof(::Type{Quantity{T, D, U}}) where {T, D, U} =
    Quantity{<:Any, D, U}
```

**Comment by rafaqz** [comment]
Using `<:Any` seems best for a pull request. Maybe even with `where T` in the constructor for a nicer show message:

```julia
Unitful.Quantity{<:Any, D, U}(val) where {D, U} = Quantity{typeof(val / unit(val)), D, U}(val)

ConstructionBase.constructorof(::Type{Unitful.Quantity{T, D, U}}) where {T, D, U} =
    Unitful.Quantity{T, D, U} where T

julia> u = 1u"m"
1 m
julia> ConstructionBase.constructorof(typeof(u))
Quantity{T,𝐋,Unitful.FreeUnits{(m,),𝐋,nothing}} where T
```

This is also interesting:
```julia
julia> typeof(u) <: ConstructionBase.constructorof(typeof(u))
true
```

I think this should be the canonical form for this reason. In DimensionalData.jl I have a basetype method used to compare types exactly like this - where the type parameters matter but the type of val doesn't. I've been wondering if it would make sense to define:
 
```
basetypeof(T) = constructorof(T)
```

Allowing for methods where this is not the case.

**Comment by tkf** [comment]
I agree `where T` version is better since the output would be more readable.

ATM, we explicitly says that

https://github.com/JuliaObjects/ConstructionBase.jl/blob/b3f1f790ebd99598dd486dfe2a8b4708f1c5c854/src/constructorof.md#L16-L34

So I think doing `basetypeof(T) = constructorof(T)` needs to change this part of the spec?  Or maybe you can use something like

```julia
function basetypeof(T)
    S = constructorof(T)
    if T isa Type && T <: S
        return T
    else
        return invoke(constructorof, Tuple{Type}, T)
    end
end
```

?

**Comment by rafaqz** [comment]
That's a good option. Just to throw a spanner in things it might even make sense if:

```julia
constructorof(T) = basetypeof(T)
```

As the the default constructor is the base type.

**Comment by tkf** [comment]
`besttypeof` is something like `constructorof` but guaranteed to hold `T <: constructorof(T)`?  I don't have a usecase in mind but maybe it is useful.  If we add this we should recommend defining `besttypeof` whenever possible instead of `constructorof`.

On the other hand, I find it a bit unclear what it means to be the "best."  Can it be application-specific?  I think we need to have well-defined spec if we are going to add this.

**Comment by rafaqz** [comment]
Its actually `basetypeof` starting with `base`!

I was thinking the definition is all the minimum type information that can't be taken from field arguments. Its a very similar concept to `constructorof`.

**Comment by tkf** [comment]
Oops, sorry, I misread the name :sweat_smile: 

> I was thinking the definition is the minimum type information that can't be taken from field arguments.

I see, that sounds useful. I actually wanted something like this before https://github.com/jw3126/Setfield.jl/pull/84

**Comment by rafaqz** [comment]
It slightly breaks the construction focus of this package, but if you think its useful I'll put in a pull request to include `basetypeof` as it's so similar to `constructorof`.

For this particular pull request idea I'm not sure if Unitful.jl should define `basetypeof` instead of `constructorof` and implement `constructorof(T) = basetypeof(T)` here. The semantics seem very logical that way and avoid the need for `invoke`. `basetype` methods would be added where the constructor is identical, and `constructorof` methods where it isn't. Like `Tuple` unfortunately...

(I put in an issue in my early days using julia asking why `Tuple` type and constructor don't line up, as `tuple`/`Tuple` seem backwards from everything else, especially when you consider how `fieldnames` works. IMHO the most glaring design flaw in julia lol)

**Comment by jw3126** [comment]
I think having `basetypeof` and `constructorof` be overloadable is adds a lot of API subtlty that must be justified by a very good usecase, befor we add it.

**Comment by rafaqz** [comment]
Ok I'll implement it in DimensionalData.jl first, and just make the rule that `constructorof` has to be a type for the use case.

The use case there is subtyping dimension types inside `@generated`. Dimensions should be extensible, and can have type parameters that DD doesn't know about. But I need to reorder tuples of passed in dimensions to match the order of the arrays dimensions - but the value type doesn't have to match. 

Its for subtyping everything about a type except the field values. It might have wider uses as well replacing custom things people are writing to do that, but maybe not. It could also be generated automatically using the same techniques I'm proposing for `constructorof`, in which case it's probably not really imporant.

**Comment by tkf** [comment]
I don't fully understand the requirement of DimensionalData.jl here but can you use this pattern? https://juliaobjects.github.io/ConstructionBase.jl/dev/#type-tips-1
