### ISSUE TITLE
Automatically generate constructorof/basetypeof for more types

### ISSUE THREAD

**Issue by rafaqz** [JuliaObjects/ConstructionBase.jl#27]
We should be able to automatically generate constructors for simple types by looking though the parameters and types fields:

```julia
using Unitful
julia> t = typeof(1u"m")
Quantity{Int64,𝐋,Unitful.FreeUnits{(m,),𝐋,nothing}}

julia> t.name.wrapper.body.body.body.parameters
svec(T, D, U)

julia> t.name.wrapper.body.body.body.types
svec(T)
```
Are there any reasons not to? If we implemented this I wouldn't need to put in a pull request to Unitful as all types would be covered, and that's probably the case for a lot of packages.

**Comment by jw3126** [comment]
At some point I discussed with @tkf about making `constructorof` "smarter". We decided against it, so that it is easier for the user to know, when to overload it and when not.

**Comment by jw3126** [comment]
Oh I did not see your discussion in the other thread https://github.com/JuliaObjects/ConstructionBase.jl/issues/26#issuecomment-541476769

**Comment by rafaqz** [comment]
Yeah that's what I though too with Flatten.jl. But writing a PR for Unitful its seems like there are low-hanging fruits that would take care of 90% of the use cases.

This anonymous function would be easy to generate from the above:
```julia
t -> Quantity{typeof(t),D,U}(t)
``` 

I guess the cutoff could be the first layer of nesting, any deeper would require a custom method.

**Comment by jw3126** [comment]
If it is possible to generate sane error messages in case where the simple heuristics fails, I am okay with a smarter `constructorof`.

**Comment by rafaqz** [comment]
I agree. If it can't account for all the types in the first level, we can throw an error that the constructor doesn't exist. We can probably suggest which parameters we can't fill automatically.

**Comment by jw3126** [comment]
If we can throw something like:
```julia
"""
...
Consider overloading ConstructionBase.constructorof(::Type{$MyType})
"""
```
that would be good enough already I think.

**Comment by tkf** [comment]
This is touching the internal of UnionAll and DataType. I'd be a bit more nervous for going 1.0 if this feature is in. I think it is possible to design types s.t you don't need a feature like this https://juliaobjects.github.io/ConstructionBase.jl/dev/#type-tips-1 and it would be bad to carry a hard to maintain feature if people started using a pattern like this.

How about implementing this outside `constructorof` and making it optional?  For example, we can add a macro `@autodefconstructor` which can be used simply by

```julia
module Unitful

... definitions ...

@autodefconstructor  # define "magic" constructorof for all `struct`s defined here

end  # module Unitful
```

Also, the code for finding "non-field" type parameters can become tricky when the type parameters are not directly the type of the fields.  (@rafaqz Is this what you meant by "the cutoff could be the first layer of nesting?")

```julia
struct MyStruct{T, N1, N2}
    a::NTuple{N1, T}
    b::NTuple{N2, T}
end
```

Another tricky case is when you can technically determine the type from constructor arguments but Julia doesn't:

```julia
struct MyStruct{T, S <: T}
    a::T
end
```

**Comment by rafaqz** [comment]
I'm not sure 1.0 should be so soon anyway! it might be better to wait a little and let things settle out. 

The macro could also be good generally, but the idea here was purely to avoid pull requests and dependency on ConstructionBase for a lot of existing types.

I don't know if this is possible without inspecting UnionAll and DataType, we need access to the link between fields and parameters.

And yes that's what I meant. If you can't work it out from the first inspection of parameters/types as I showed above, don't dig any deeper because the complexity will get out of hand. Both of those examples would be skipped and give the error message asking to define a custom constructor. But in Unitful the simple method would provide all of the constructors, and I think that will be the case a lot of the time.

I'm focussed on Unitful as it blocks a release of Flatten.jl due to `constructorof(::Quantity)` now being type pyracy.

**Comment by tkf** [comment]
I think using heuristics to determine when to define `constructorof` can cause troubles.  For example currently we have

```julia
struct Quantity{T,D,U} <: ...
    val::T
    ...
end
```

but Unitful.jl devs may decide to do some "refactoring" to do

```julia
struct Quantity{T<:Number,D,U} <: ...
    val::T
    ...
end
```

which, AFAICT, a backward compatible change for them.  But then this now maybe crosses the heuristic cutoff?  Even this example is not the problem, I think there might be some examples where a backward compatible change causes trouble for `constructorof` users.

I think this situation is much worse as now `constructorof` users (like you) need to convince upstream packages to use ConstructionBase.jl _after_ developing code that requires a functional `constructorof` definition.

**Comment by rafaqz** [comment]
That example wouldn't be a problem, it's just swapping `Any` for `Number` in the ub field of TypeVar, which wouldn't be considered - only the `name` field. 

I can't see how it would be a problem with this particular cutoff for a non-breaking change, but it would be good to be sure of that before proceeding.

**Comment by tkf** [comment]
Changing

```julia
struct MyStruct1{A}
    a::A
    MyStruct1(A::NTuple) = new{typeof(A)}(A)
end
```

to

```julia
struct MyStruct2{T, N, A <: NTuple{N, T}}
    a::A
end
```

could be considered a backward-compatible change (unless type parameters are documented) but wouldn't it cause a trouble with `constructorof` with the heuristics?

**Comment by rafaqz** [comment]
That's would be a breaking change in a lot of packages, but you're right it might not be in others. I'm not clear on wether the parameters of an exported type are part of the api or not.  

But I'm convinced anyway, the complexity will get out of hand. Pull requests it is.
