### ISSUE TITLE
Do I have admin access?

### ISSUE THREAD

**Issue by tkf** [JuliaObjects/ConstructionBase.jl#3]
It looks like I can't change the setting of this repository.  I can't see `Settings` tab:

![image](https://user-images.githubusercontent.com/29282/65842446-8a28eb80-e2e0-11e9-919a-37528ae024d1.png)

Looking at https://github.com/orgs/JuliaObjects/people, I'm a `Member` but perhaps changing settings require `Owner`?

**Comment by jw3126** [comment]
Should work now.
