### ISSUE TITLE
Constructing anonymous functions

### ISSUE THREAD

**Issue by rafaqz** [JuliaObjects/ConstructionBase.jl#32]
I've just come accross some cases where anonymous function fields can be handy to update. Treating them as model parameters can lead to very nice scripting syntax. It avoids writing structs and separate methods for them, and renaming the structs whenever you make changes.

But they don't actually have a constructor, so Setfield.jl/Flatten.jl can't change the fields.

Eg. this doesn't work:

```julia
julia> using Flatten

julia> f = let a=1, b=1
           x -> a*x + b
       end
#125 (generic function with 1 method)

julia> f(1)
2

julia> f = Flatten.reconstruct(f, (2, 2))
ERROR: MethodError: no method matching var"#125#126"(::Int64, ::Int64)
Stacktrace:
 [1] macro expansion at /home/raf/.julia/packages/Flatten/oXoLY/src/Flatten.jl:197 [inlined]
 [2] reconstruct(::var"#125#126"{Int64,Int64}, ::Tuple{Int64,Int64}, ::typeof(flattenable), ::Type{Real}, ::Type{Flatten.EmptyIgnore}, ::Int64) at /home/raf/.julia/packages/Flatten/oXoLY/src/Flatten.jl:193
 [3] reconstruct(::Function, ::Tuple{Int64,Int64}, ::Function, ::Type{T} where T, ::Type{T} where T) at /home/raf/.julia/packages/Flatten/oXoLY/src/Flatten.jl:186
 [4] reconstruct at /home/raf/.julia/packages/Flatten/oXoLY/src/Flatten.jl:184 [inlined]
 [5] reconstruct at /home/raf/.julia/packages/Flatten/oXoLY/src/Flatten.jl:183 [inlined]
 [6] reconstruct(::Function, ::Tuple{Int64,Int64}) at /home/raf/.julia/packages/Flatten/oXoLY/src/Flatten.jl:181
 [7] top-level scope at REPL[95]:1
 [8] eval(::Module, ::Any) at ./boot.jl:331
 [9] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [10] run_backend(::REPL.REPLBackend) at /home/raf/.julia/packages/Revise/BqeJF/src/Revise.jl:1184
 [11] top-level scope at none:0
```

But we can define a macro to define the struct again (maybe there's an even simpler way?)

```julia
macro construct_anon(x)
    T = eval(:(typeof($x)))
    structname = esc(T.name.name)
    fns = fieldnames(T))
    Expr(:struct, false, 
        Expr(
            :(<:), 
            Expr(:curly, structname, [esc(fn) for fn in fns]...), 
            :Function
        ),
        Expr(:block, [Expr(:(::), fn, esc(fn)) for fn in fns]...),
    )
end
```

Then:

```julia
julia> @construct_anon f

julia> f = Flatten.reconstruct(f, (2, 2))
#125 (generic function with 1 method)

julia> f(1)
4
```

Anyway, I'm not sure where to put this code, but thought it might be interesting to share in case others encounter it. Maybe we can start another package some time with macros and tricks like this in it.

**Comment by jw3126** [comment]
Not sure if the fields of an anonymous function are part of the stable API? Another approach might be to have convenient syntax for declaring a struct and its call method in one go:
```julia
@macroexpand @lambda f(a,b)(x) = a*x+b
```
Gives something like
```julia
struct F{A,B}; a::A; b::B; end
(f::F)(x) = f.a*x+f.b
```
Would that also solve your original problem? Can you declare your lambda at top level or do you want to do this e.g. inside of a function?

**Comment by rafaqz** [comment]
That's the other option I'm considering.

I'm not sure about the api, but anonymous function fields have been there for a long time, and get in the way sometimes anyway. For example, If you have a model that contains an anonymous function with fields and you run `Flatten.flatten(model)` they are returned along with every other field. `Flatten.reconstruct(model, vals)` will try to rebuild them and `constructorof` will fail trying. (`Flatten.reconstruct(f, Number, Function)` will avoid it).

I hadn't realized there are actually structs with fields but no constructors before trying this. It's interesting to note for this package.

**Comment by tkf** [comment]
If you need a quick hack https://discourse.julialang.org/t/is-there-a-way-to-modify-captured-variables-in-a-closure/31213/12 is the one using `@generated`.

But I think something explicit like @jw3126 is the way to go if you want to have a callable object that is reconstructable.

> For example, If you have a model that contains an anonymous function with fields and you run `Flatten.flatten(model)` they are returned along with every other field.

For this particular usecase, do you need to reconstruct the closures?  If not, would it help to have (say) `AnonymousFunction` abstract type used as a supertype of the closures?  You can then stop recursing the object tree by dispatching on `AnonymousFunction`.  I think it is worth opening an issue since there is some chance we can put it in `Core`.

**Comment by jw3126** [comment]
I learned this from @masonprotter at slack:
```julia
julia> macro new(T, args...)
           (esc ∘ Expr)(:new, T, args...)
       end
@new (macro with 1 method)

julia> function adder(a)
           x -> x + a
       end
adder (generic function with 1 method)

julia> adder(1).a
1

julia> add42 = @new typeof(adder(1)) 42
#3 (generic function with 1 method)

julia> add42(0)
42
```

**Comment by rafaqz** [comment]
I finally got around to writing this up for `constructorof`.

ConstructionBase methods:

```julia
struct FunctionConstructor{F} end

@generated function (::FunctionConstructor{F})(args...) where F
    exp = Expr(:new, F)
    for i in 1:length(F.parameters)
        push!(exp.args, :(args[$i]))
    end
    exp
end

function ConstructionBase.constructorof(f::F) where F <: Function
    FunctionConstructor{F}()
end
```

Define a function that returns an anonymous function:

```julia
function adder3(a, b, c)
    x -> x + a + b + c
end
```

And it works!!

```julia
julia> add111 = adder3(1, 1, 1)
#27 (generic function with 1 method)

julia> add123 = ConstructionBase.constructorof(add111)(1,2,3)
#27 (generic function with 1 method)

julia> add111(2)
5

julia> add123(2)
8
```

**Comment by jw3126** [comment]
Cool! I think this needs some tweaks, so that the following works:
```julia
julia> add123 = ConstructionBase.constructorof(typeof(add111))(1,2,3.0)
ERROR: TypeError: in new, expected Int64, got a value of type Float64
```
Then we could include it here.

**Comment by rafaqz** [comment]
Oh nice catch. This is generic:

```julia
@generated function (::FunctionConstructor{F})(args...) where F
    curly = Expr(:curly, F.name.wrapper)
    for arg in args
        push!(curly.args, arg)
    end
    exp = Expr(:new, curly)
    for i in 1:length(args)
        push!(exp.args, :(args[$i]))
    end
    return exp
end
````
