### ISSUE TITLE
tag v1.1.0

### ISSUE THREAD

**Issue by nico202** [JuliaObjects/ConstructionBase.jl#42]
Would you mind tagging the latest version?

Thanks, Nicolo'

**Comment by rafaqz** [comment]
Oops thought I had!!

**Comment by rafaqz** [comment]
Its odd that tagbot didn't do that automatically. Something may not be set up correctly here.

**Comment by rafaqz** [comment]
Ok this is tagged, and Tagbot is updated so hopefully this is automatic from now on.
