### ISSUE TITLE
ConstructionBaseFunctions.jl?

### ISSUE THREAD

**Issue by rafaqz** [JuliaObjects/ConstructionBase.jl#44]
I've been thinking we could just pull out the functions here so we have a 3 line package for other packages to add method definitions to for their own types, without generated functions etc complicating the issue of adding a dependency.

The whole thing would be just the functions to extend:

```julia
function constructorof end
function setproperties end
function getproperties end
```

Is there any problem with doing that? It would also free us up to put more object definitions in ConstructionBase.jl and worry a little less about how light-weight it is.

See https://github.com/JuliaArrays/StaticArrays.jl/pull/901

**Comment by jw3126** [comment]
At the moment I think `ConstructionBase.jl` is already lightweight enough. That being said, if potential adopters see this differently or if there is a concrete vision that makes `ConstuctionBase.jl` heavier, I am open to splitting these lines out (`ConstructionBaseStubs.jl` would be another name suggestion).
From a quick glance at the discussion you linked, it seems that heaviness was not raised as a concern by StaticArrays maintainers?

**Comment by rafaqz** [comment]
Adding a dependency was raised as a concern in the related issue that PR closes. Not sure how widely that ci cern is held.

**Comment by jw3126** [comment]
Would be really nice to be better integrated with StaticArrays, so if they require a smaller dependency, we should go for it.

**Comment by rafaqz** [comment]
Absolutely. It's interesting that they have a bunch of similar methods already, like `similar_type`.

**Comment by rafaqz** [comment]
Solved in a slightly different way with https://github.com/JuliaObjects/ConstructionBaseExtras.jl
