### ISSUE TITLE
getproperties on Tuples?

### ISSUE THREAD

**Issue by jw3126** [JuliaObjects/ConstructionBase.jl#49]
```julia
julia> using ConstructionBase

julia> getproperties((1,2,))
ERROR: TypeError: in NamedTuple, in name, expected Symbol, got a value of type Int64
Stacktrace:
 [1] (NamedTuple{(1, 2), T} where T<:Tuple)(args::Tuple{Int64, Int64})
   @ Core ./boot.jl:591
 [2] macro expansion
   @ ~/.julia/packages/ConstructionBase/8o3I5/src/ConstructionBase.jl:44 [inlined]
 [3] getproperties(obj::Tuple{Int64, Int64})
   @ ConstructionBase ~/.julia/packages/ConstructionBase/8o3I5/src/ConstructionBase.jl:44
 [4] top-level scope
   @ REPL[5]:1
```
What should `getproperties` do on `Tuple`? Some options are:
* Return `NamedTuple()`
* throw an error
* Return the tuple itself

Similar question for `setproperties`.

**Comment by rafaqz** [comment]
`NamedTuple` should just allow `Int` keys as well as `Symbol` for consistency with `fieldnames` ;)

But I guess return a `Tuple`? and `setproperties` accepts a `Tuple`? That way it wont need special-casing in Accesors.jl and elsewhere a lot of the time

An error or `NamedTuple()` might be a bit odd given that

```julia
julia> propertynames((3,4))
(1, 2)
```
