### ISSUE TITLE
Actually use properties, not fields

### ISSUE THREAD

**Issue by aplavin** [JuliaObjects/ConstructionBase.jl#59]
Both `getproperties` and `setproperties` are documented to relate to struct properties and not its fields.
However, the implementation is very inconsistent in fields vs properties.
Calling `fieldnames` and then `getproperties`:
https://github.com/JuliaObjects/ConstructionBase.jl/blob/2044dd59b61c701b66ab43fc4b4326573c126095/src/ConstructionBase.jl#L47-L49
Reporting `fieldnames` in the error message:
https://github.com/JuliaObjects/ConstructionBase.jl/blob/2044dd59b61c701b66ab43fc4b4326573c126095/src/ConstructionBase.jl#L91

These inconsistencies lead to confusing errors, e.g.:
```julia
julia> using ConstructionBase, StructArrays

julia> s = StructArray(a=1:5)
5-element StructArray(::UnitRange{Int64}) with eltype NamedTuple{(:a,), Tuple{Int64}}:
 (a = 1,)
 (a = 2,)
 (a = 3,)
 (a = 4,)
 (a = 5,)

julia> fieldnames(typeof(s))
(:components,)

julia> propertynames(s)
(:a,)

julia> getproperties(s)
ERROR: type NamedTuple has no field components
# ConstructionBase tries to call getproperty(s, :components) which clearly doesn't exist
```

Maybe, `getproperties`
https://github.com/JuliaObjects/ConstructionBase.jl/blob/2044dd59b61c701b66ab43fc4b4326573c126095/src/ConstructionBase.jl#L46-L53
can be replaced with
```julia
@inline function getproperties(obj)
    fnames = propertynames(obj)
    NamedTuple{fnames}(getproperty.(Ref(obj), fnames))
end
```
? It infers just fine on 1.7+.

**Comment by jw3126** [comment]
Wow nice! We would love to get rid of fieldnames usage as much as possible. I tried quite a bit in the past, but mostly failed. If your suggestions passes the test suite (on 1.7+), that would be awesome!
