### ISSUE TITLE
reconstruct(::Type, args...) vs constructorof(::Type)(args...)

### ISSUE THREAD

**Issue by tkf** [JuliaObjects/ConstructionBase.jl#7]
Since `constructorof` is used mainly for overloading especially for end-users, it is better be optimized for ease of defining it.  So, it _may_ make sense to use an API (say) `reconstruct(::Type, args...)` instead of `constructorof(::Type)(args...)` because `reconstruct` makes it easier to dispatch on argument types.  You can still do

```julia
function constructorof(::Type{<:MyType})
    constructor(x::Real) = MyType(x)
    constructor(x::Complex) = MyType(x; complex=true)
    return constructor
end
```

but some people treat defining multiple methods for a closure a code smell.

Having said that, I still think `constructorof` is the way to go, as you should not have special code path for re-constructing object.  It should be only about "routing" to the right method (e.g., filling type parameters).  What do you think?

**Comment by jw3126** [comment]
Not sure. I must say, that I do not overload `constructorof` much. Most of my types work out of the box and the others are so elaborate, that their fields are an implementation detail and I need to overload `setproperties` directly.

**Comment by tkf** [comment]
I think one common pattern might be to opt-out type-changing behavior:

```julia
constructorof(::Type{T}) where {T <: MyType} = T
```

I use it in a few places; e.g. https://github.com/tkf/Transducers.jl/blob/73c90d9e99cb4256c1471e8596710c8fae26a211/src/core.jl#L220

This is why I thought `constructorof` would only require to do "routing."

@rafaqz Do you have any preference?  Otherwise, I'd say let's go with `constructorof`.

**Comment by jw3126** [comment]
That is a nice use case.

**Comment by tkf** [comment]
As we are already releasing this package, I'll close this issue for now until we accumulate enough real usecases for the `reconstruct` approach.  Those approaches are "isomorphic" so it shouldn't be a huge issue.

**Comment by rafaqz** [comment]
I use both of these methods in different packages. But normally reconstruct has more package specific behaviours attached, as in DimensionalData.jl. Defining `constructorof` is generally easier so I would go with that for now.

**Comment by tkf** [comment]
Thanks for the comment. That's a relief!
